/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package calculadora;

import java.util.ArrayList;
import pilas.PilaA; //


/**
 *
 * @author Mariela Mejia
 */
public class InterfazCalculadora extends javax.swing.JFrame {
    private String cad;
    private String univ; 
    private ArrayList<String> infijo; 
    
    /**
     * Creates new form InterfazCalculadora
     */
    public InterfazCalculadora() {
        initComponents();
        infijo = new ArrayList(); 
        cad="";
        univ="";
    }
    /**
     * instancia variable cadena con el valor dado
     * @param s String
     */
    public void setCadena(String s){
        cad = s; 
    }
    
    /**
     * devuelve variable cadena
     * @return regresa cadena 
     */
    public String getCadena (){
        return cad; 
    }
    
    /**
     * devuelve la cadena universal
     * @return regresa cadena universal
     */
    public String getUniversal(){
        return univ;
    }
    /**
     * Instanciacion de cadena universal
     * @param univ crea la cadena universal con el valor dado
     */
    public void setUniversal(String univ){
        this.univ = univ;
    }

    /**
     * Devuelve ArrayList del metodo infijo
     * @return regresa ArrayList
     */
    public String getArrayList(){
        return infijo.toString(); 
    }
    /**
     * Agrega al metodo infijo un valor al final
     * @param s valor para agregar
     */
    public void agregaArrayList(String s){
        this.infijo.add(s); 
    }
    /**
     * Modifica el valor de una celda de la lista con el valor dado
     * @param s nuevo valor
     * @param n posicion a insertar
     */
    public void modificaArray(String s, int n){
        this.infijo.set(n, s);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btUno = new javax.swing.JButton();
        btDos = new javax.swing.JButton();
        btTres = new javax.swing.JButton();
        btCuatro = new javax.swing.JButton();
        btCinco = new javax.swing.JButton();
        btSeis = new javax.swing.JButton();
        btSiete = new javax.swing.JButton();
        btOcho = new javax.swing.JButton();
        btNueve = new javax.swing.JButton();
        btCero = new javax.swing.JButton();
        btPunto = new javax.swing.JButton();
        btSuma = new javax.swing.JButton();
        btResta = new javax.swing.JButton();
        btMultipl = new javax.swing.JButton();
        btDivision = new javax.swing.JButton();
        btPotencia = new javax.swing.JButton();
        btParenteAbre = new javax.swing.JButton();
        btParentesCierra = new javax.swing.JButton();
        btCambiaSigno = new javax.swing.JButton();
        btBorrarUltimoElemento = new javax.swing.JButton();
        btClear = new javax.swing.JButton();
        btIgual = new javax.swing.JButton();
        panelPrincipal = new javax.swing.JLabel();
        panelResultado = new javax.swing.JLabel();
        fondoInterface = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setName("interfazCalculadora"); // NOI18N
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btUno.setBackground(new java.awt.Color(153, 153, 153));
        btUno.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btUno.setText("1");
        btUno.setPreferredSize(new java.awt.Dimension(60, 40));
        btUno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btUnoActionPerformed(evt);
            }
        });
        getContentPane().add(btUno, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, -1, -1));

        btDos.setBackground(new java.awt.Color(153, 153, 153));
        btDos.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btDos.setText("2");
        btDos.setPreferredSize(new java.awt.Dimension(60, 40));
        btDos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDosActionPerformed(evt);
            }
        });
        getContentPane().add(btDos, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 400, 60, -1));

        btTres.setBackground(new java.awt.Color(153, 153, 153));
        btTres.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btTres.setText("3");
        btTres.setPreferredSize(new java.awt.Dimension(60, 40));
        btTres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTresActionPerformed(evt);
            }
        });
        getContentPane().add(btTres, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 400, -1, -1));

        btCuatro.setBackground(new java.awt.Color(153, 153, 153));
        btCuatro.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btCuatro.setText("4");
        btCuatro.setPreferredSize(new java.awt.Dimension(60, 40));
        btCuatro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCuatroActionPerformed(evt);
            }
        });
        getContentPane().add(btCuatro, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, -1, -1));

        btCinco.setBackground(new java.awt.Color(153, 153, 153));
        btCinco.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btCinco.setText("5");
        btCinco.setPreferredSize(new java.awt.Dimension(60, 40));
        btCinco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCincoActionPerformed(evt);
            }
        });
        getContentPane().add(btCinco, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 330, -1, -1));

        btSeis.setBackground(new java.awt.Color(153, 153, 153));
        btSeis.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btSeis.setText("6");
        btSeis.setPreferredSize(new java.awt.Dimension(60, 40));
        btSeis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSeisActionPerformed(evt);
            }
        });
        getContentPane().add(btSeis, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 330, -1, -1));

        btSiete.setBackground(new java.awt.Color(153, 153, 153));
        btSiete.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btSiete.setText("7");
        btSiete.setPreferredSize(new java.awt.Dimension(60, 40));
        btSiete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSieteActionPerformed(evt);
            }
        });
        getContentPane().add(btSiete, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, -1, -1));

        btOcho.setBackground(new java.awt.Color(153, 153, 153));
        btOcho.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btOcho.setText("8");
        btOcho.setPreferredSize(new java.awt.Dimension(60, 40));
        btOcho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btOchoActionPerformed(evt);
            }
        });
        getContentPane().add(btOcho, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 260, -1, -1));

        btNueve.setBackground(new java.awt.Color(153, 153, 153));
        btNueve.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btNueve.setText("9");
        btNueve.setPreferredSize(new java.awt.Dimension(60, 40));
        btNueve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNueveActionPerformed(evt);
            }
        });
        getContentPane().add(btNueve, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 260, -1, -1));

        btCero.setBackground(new java.awt.Color(153, 153, 153));
        btCero.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btCero.setText("0");
        btCero.setPreferredSize(new java.awt.Dimension(60, 40));
        btCero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCeroActionPerformed(evt);
            }
        });
        getContentPane().add(btCero, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 460, -1, -1));

        btPunto.setBackground(new java.awt.Color(153, 153, 153));
        btPunto.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btPunto.setText(".");
        btPunto.setPreferredSize(new java.awt.Dimension(60, 40));
        btPunto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPuntoActionPerformed(evt);
            }
        });
        getContentPane().add(btPunto, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 460, -1, -1));

        btSuma.setBackground(new java.awt.Color(153, 153, 153));
        btSuma.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btSuma.setText("+");
        btSuma.setPreferredSize(new java.awt.Dimension(60, 40));
        btSuma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSumaActionPerformed(evt);
            }
        });
        getContentPane().add(btSuma, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 460, -1, -1));

        btResta.setBackground(new java.awt.Color(153, 153, 153));
        btResta.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btResta.setText("-");
        btResta.setPreferredSize(new java.awt.Dimension(60, 40));
        btResta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRestaActionPerformed(evt);
            }
        });
        getContentPane().add(btResta, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 400, -1, -1));

        btMultipl.setBackground(new java.awt.Color(153, 153, 153));
        btMultipl.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btMultipl.setText("*");
        btMultipl.setPreferredSize(new java.awt.Dimension(60, 40));
        btMultipl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMultiplActionPerformed(evt);
            }
        });
        getContentPane().add(btMultipl, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 400, -1, -1));

        btDivision.setBackground(new java.awt.Color(153, 153, 153));
        btDivision.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btDivision.setText("/");
        btDivision.setPreferredSize(new java.awt.Dimension(60, 40));
        btDivision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDivisionActionPerformed(evt);
            }
        });
        getContentPane().add(btDivision, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 330, -1, -1));

        btPotencia.setBackground(new java.awt.Color(153, 153, 153));
        btPotencia.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btPotencia.setText("^");
        btPotencia.setPreferredSize(new java.awt.Dimension(60, 40));
        btPotencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPotenciaActionPerformed(evt);
            }
        });
        getContentPane().add(btPotencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 330, -1, -1));

        btParenteAbre.setBackground(new java.awt.Color(153, 153, 153));
        btParenteAbre.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btParenteAbre.setText("(");
        btParenteAbre.setPreferredSize(new java.awt.Dimension(60, 40));
        btParenteAbre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btParenteAbreActionPerformed(evt);
            }
        });
        getContentPane().add(btParenteAbre, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 260, -1, -1));

        btParentesCierra.setBackground(new java.awt.Color(153, 153, 153));
        btParentesCierra.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btParentesCierra.setText(")");
        btParentesCierra.setPreferredSize(new java.awt.Dimension(60, 40));
        btParentesCierra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btParentesCierraActionPerformed(evt);
            }
        });
        getContentPane().add(btParentesCierra, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 260, -1, -1));

        btCambiaSigno.setBackground(new java.awt.Color(102, 102, 102));
        btCambiaSigno.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btCambiaSigno.setText("+/-");
        btCambiaSigno.setPreferredSize(new java.awt.Dimension(60, 40));
        btCambiaSigno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCambiaSignoActionPerformed(evt);
            }
        });
        getContentPane().add(btCambiaSigno, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, 70, -1));

        btBorrarUltimoElemento.setBackground(new java.awt.Color(102, 102, 102));
        btBorrarUltimoElemento.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btBorrarUltimoElemento.setText("Borrar");
        btBorrarUltimoElemento.setPreferredSize(new java.awt.Dimension(60, 40));
        btBorrarUltimoElemento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBorrarUltimoElementoActionPerformed(evt);
            }
        });
        getContentPane().add(btBorrarUltimoElemento, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 200, 70, -1));

        btClear.setBackground(new java.awt.Color(102, 102, 102));
        btClear.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btClear.setText("Clear");
        btClear.setPreferredSize(new java.awt.Dimension(60, 40));
        btClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btClearActionPerformed(evt);
            }
        });
        getContentPane().add(btClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 200, -1, -1));

        btIgual.setBackground(new java.awt.Color(153, 153, 153));
        btIgual.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btIgual.setText("=");
        btIgual.setPreferredSize(new java.awt.Dimension(60, 40));
        btIgual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btIgualActionPerformed(evt);
            }
        });
        getContentPane().add(btIgual, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 460, -1, -1));

        panelPrincipal.setBackground(new java.awt.Color(153, 153, 153));
        panelPrincipal.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        panelPrincipal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        panelPrincipal.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        panelPrincipal.setOpaque(true);
        getContentPane().add(panelPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 340, 50));

        panelResultado.setBackground(new java.awt.Color(153, 153, 153));
        panelResultado.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        panelResultado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        panelResultado.setOpaque(true);
        getContentPane().add(panelResultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 340, 50));

        fondoInterface.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calculadora/fondo.jpg"))); // NOI18N
        getContentPane().add(fondoInterface, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents
/**
 * Ingresa el punto (.)
 * @param evt 
 */
    private void btPuntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPuntoActionPerformed
        setCadena(cad + ".");
        setUniversal(univ + ".");
        this.panelPrincipal.setText(univ);
    }//GEN-LAST:event_btPuntoActionPerformed
/**
 * Ingresa el numero uno (1)
 * @param evt 
 */
    private void btUnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btUnoActionPerformed
        setCadena(cad + "1");
        setUniversal(univ + "1");
        this.panelPrincipal.setText(univ);
    }//GEN-LAST:event_btUnoActionPerformed
/**
 * Ingresa el numero dos (2)
 * @param evt 
 */
    private void btNueveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNueveActionPerformed
        setCadena(cad + "9"); 
        setUniversal(univ + "9");
        this.panelPrincipal.setText(univ);
    }//GEN-LAST:event_btNueveActionPerformed
/**
 * Ingresa la operacion suma (+)
 * @param evt 
 */
    private void btSumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSumaActionPerformed
        if(!cad.equals(""))
            agregaArrayList(cad); 
        agregaArrayList("+"); 
        setUniversal(univ + "+"); 
        this.panelPrincipal.setText(univ); 
        setCadena(""); 
    }//GEN-LAST:event_btSumaActionPerformed
/**
 * Ingresa la operacion potencia (^)
 * @param evt 
 */
    private void btPotenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPotenciaActionPerformed
        if(!cad.equals(""))
            agregaArrayList(cad); 
        agregaArrayList("^"); 
        setUniversal(univ + "^"); 
        this.panelPrincipal.setText(univ); 
        setCadena(""); 
    }//GEN-LAST:event_btPotenciaActionPerformed
/**
 * Ingresa el numero tres (3)
 * @param evt 
 */
    private void btTresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTresActionPerformed
        setCadena(cad + "3"); 
        setUniversal(univ + "3");
        this.panelPrincipal.setText(univ);
    }//GEN-LAST:event_btTresActionPerformed
/**
 * Ingresa la operacion resta (-)
 * @param evt 
 */
    private void btRestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRestaActionPerformed
        if(!cad.equals(""))
            agregaArrayList(cad); 
        agregaArrayList("-"); 
        setUniversal(univ + "-"); 
        this.panelPrincipal.setText(univ); 
        setCadena(""); 
    }//GEN-LAST:event_btRestaActionPerformed
/**
 * Ingresa el numero cero (0)
 * @param evt 
 */
    private void btCeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCeroActionPerformed
        setCadena(cad + "0"); 
        setUniversal(univ + "0");
        this.panelPrincipal.setText(univ);
    }//GEN-LAST:event_btCeroActionPerformed
/**
 * Ingresa la operacion igual (=) y finaliza una etapa del metodo
 * @param evt 
 */
    private void btIgualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btIgualActionPerformed
        // TODO add your handling code here:
        if(!cad.equals("")){
            agregaArrayList(cad);
            setUniversal(cad);
        }
        setCadena("");
        if(infijo.isEmpty())
            this.panelResultado.setText(univ);
        else{
            if(!Calculadora.revisaArray(infijo))
                this.panelResultado.setText("SYNTAX ERROR");
            else{
                setUniversal(Calculadora.imprimeArray(infijo));
                ArrayList<String> postfijo = Calculadora.escribePostfijo(infijo);
                PilaA<Double> aux = new PilaA();
                int i=0;
                boolean bandera = true;
                while(i<postfijo.size() && bandera){
                    if(!Calculadora.esOperador(postfijo.get(i)))
                        aux.push(Double.parseDouble(postfijo.get(i)));
                    else{
                        double b = aux.pop();
                        double a = aux.pop();
                        switch(postfijo.get(i)){
                            case "+" -> aux.push(a+b);
                            case "-" -> aux.push(a-b);
                            case "*" -> aux.push(a*b);
                            case "/" -> {
                                if(b == 0){
                                    bandera = false;
                                    this.panelResultado.setText("MATH ERROR");
                                }
                                else
                                    aux.push(a/b);
                            }   
                            case "^" -> aux.push(Math.pow(a,b));
                        }
                    }
                    i++;
                }
                if(bandera == true && i == postfijo.size())
                    this.panelResultado.setText("" + aux.pop());
            }  
        }
    }//GEN-LAST:event_btIgualActionPerformed
/**
 * Ingresa la operacion multiplicacion (*)
 * @param evt 
 */
    private void btMultiplActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMultiplActionPerformed
        if(!cad.equals(""))
            agregaArrayList(cad); 
        agregaArrayList("*"); 
        setUniversal(univ + "*"); 
        this.panelPrincipal.setText(univ); 
        setCadena(""); 
    }//GEN-LAST:event_btMultiplActionPerformed
/**
 * Ingresa el numero dos (2)
 * @param evt 
 */
    private void btDosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDosActionPerformed
        setCadena(cad + "2"); 
        setUniversal(univ + "2");
        this.panelPrincipal.setText(univ);
    }//GEN-LAST:event_btDosActionPerformed
/**
 * Ingresa el numero cuatro (4)
 * @param evt 
 */
    private void btCuatroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCuatroActionPerformed
        setCadena(cad + "4"); 
        setUniversal(univ + "4");
        this.panelPrincipal.setText(univ);
    }//GEN-LAST:event_btCuatroActionPerformed
/**
 * Ingresa el numero cinco (5)
 * @param evt 
 */
    private void btCincoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCincoActionPerformed
        setCadena(cad + "5"); 
        setUniversal(univ + "5");
        this.panelPrincipal.setText(univ);
    }//GEN-LAST:event_btCincoActionPerformed
/**
 * Ingresa el numero seis (6)
 * @param evt 
 */
    private void btSeisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSeisActionPerformed
        setCadena(cad + "6"); 
        setUniversal(univ + "6");
        this.panelPrincipal.setText(univ);
    }//GEN-LAST:event_btSeisActionPerformed
/**
 * Ingresa la operacion division (/)
 * @param evt 
 */
    private void btDivisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDivisionActionPerformed
        if(!cad.equals(""))
            agregaArrayList(cad); 
        agregaArrayList("/"); 
        setUniversal(univ + "/"); 
        this.panelPrincipal.setText(univ); 
        setCadena(""); 
    }//GEN-LAST:event_btDivisionActionPerformed
/**
 * Limpia la pantalla y reinicia valores de la cadena
 * @param evt 
 */
    private void btClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btClearActionPerformed
        infijo.clear();
        this.panelPrincipal.setText("");
        this.panelResultado.setText("");
        setUniversal("");
        setCadena("");
    }//GEN-LAST:event_btClearActionPerformed
/**
 * Ingresa el numero ocho (8)
 * @param evt 
 */
    private void btOchoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btOchoActionPerformed
        setCadena(cad + "8"); 
        setUniversal(univ + "8");
        this.panelPrincipal.setText(univ);
    }//GEN-LAST:event_btOchoActionPerformed
/**
 * Ingresa el numero siete (7)
 * @param evt 
 */
    private void btSieteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSieteActionPerformed
        setCadena(cad + "7"); 
        setUniversal(univ + "7");
        this.panelPrincipal.setText(univ);
    }//GEN-LAST:event_btSieteActionPerformed
/**
 * Ingresa parentesis de apertura ("(")
 * @param evt 
 */
    private void btParenteAbreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btParenteAbreActionPerformed
        if(!cad.equals(""))
            agregaArrayList(cad); 
        agregaArrayList("("); 
        setUniversal(univ + "("); 
        this.panelPrincipal.setText(univ); 
        setCadena(""); 
    }//GEN-LAST:event_btParenteAbreActionPerformed
/**
 * Ingresa parenesis de cierre (")")
 * @param evt 
 */
    private void btParentesCierraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btParentesCierraActionPerformed
        if(!cad.equals(""))
            agregaArrayList(cad); 
        agregaArrayList(")"); 
        setUniversal(univ + ")"); 
        this.panelPrincipal.setText(univ); 
        setCadena(""); 
    }//GEN-LAST:event_btParentesCierraActionPerformed
/**
 * Elimina ultimo digito agregado a la cadena 
 * @param evt 
 */
    private void btBorrarUltimoElementoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBorrarUltimoElementoActionPerformed
        if(infijo.isEmpty())
            if(cad.equals(""))
                setUniversal("");
            else{
                setCadena("");
                setUniversal(cad);
            }
        
        else
            if(cad.equals("")){
                infijo.remove(infijo.size() - 1);
                setUniversal(Calculadora.imprimeArray(infijo));
            }
            else{
                setCadena("");
                setUniversal(Calculadora.imprimeArray(infijo) + cad);
            }
        this.panelPrincipal.setText(univ);
    }//GEN-LAST:event_btBorrarUltimoElementoActionPerformed
/**
 * Cambia de signo el ultimo valor numerico para utilizarse como negativo
 * @param evt 
 */
    private void btCambiaSignoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCambiaSignoActionPerformed
        if(!cad.equals("")){
            setCadena(Calculadora.cambiaDeSigno(cad));
            setUniversal(Calculadora.imprimeArray(infijo) + cad);
        }
        else
            if(!infijo.isEmpty())
                if(!Calculadora.esOperador(infijo.get( infijo.size() - 1 )) && !infijo.get( infijo.size() - 1 ).equals("(") && !infijo.get( infijo.size() - 1 ).equals(")")){
                    modificaArray(Calculadora.cambiaDeSigno(infijo.get(infijo.size()-1)), infijo.size()-1);
                    setUniversal(Calculadora.imprimeArray(infijo));
                }
        this.panelPrincipal.setText(univ);
    }//GEN-LAST:event_btCambiaSignoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazCalculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JButton btBorrarUltimoElemento;
    protected javax.swing.JButton btCambiaSigno;
    protected javax.swing.JButton btCero;
    protected javax.swing.JButton btCinco;
    protected javax.swing.JButton btClear;
    protected javax.swing.JButton btCuatro;
    protected javax.swing.JButton btDivision;
    protected javax.swing.JButton btDos;
    protected javax.swing.JButton btIgual;
    protected javax.swing.JButton btMultipl;
    protected javax.swing.JButton btNueve;
    protected javax.swing.JButton btOcho;
    protected javax.swing.JButton btParenteAbre;
    protected javax.swing.JButton btParentesCierra;
    protected javax.swing.JButton btPotencia;
    protected javax.swing.JButton btPunto;
    protected javax.swing.JButton btResta;
    protected javax.swing.JButton btSeis;
    protected javax.swing.JButton btSiete;
    protected javax.swing.JButton btSuma;
    protected javax.swing.JButton btTres;
    protected javax.swing.JButton btUno;
    private javax.swing.JLabel fondoInterface;
    private javax.swing.JLabel panelPrincipal;
    private javax.swing.JLabel panelResultado;
    // End of variables declaration//GEN-END:variables
}
